#!/usr/bin/env python3
"""Render SBOM.md (the human-readable SBOM) from sbom.cdx.json.

Usage:
  python3 scripts/sbom-md.py           regenerate SBOM.md in place
  python3 scripts/sbom-md.py --check   exit 1 if SBOM.md is out of date
                                       (CI runs this so the two never drift)

Layout: a sorted Summary table up top, each component linking to its entry
in the sorted Components & dependencies section below; entries list the
component's details plus its dependencies (and what requires it), linked.
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BOM = ROOT / "sbom.cdx.json"
OUT = ROOT / "SBOM.md"


def slug(name: str) -> str:
    """GitHub heading anchor: lowercase, drop punctuation, spaces to dashes."""
    return re.sub(r"[^\w\- ]", "", name).lower().replace(" ", "-")


def prop(comp: dict, key: str) -> str:
    for p in comp.get("properties", []):
        if p["name"] == key:
            return p["value"]
    return ""


def licenses(comp: dict) -> str:
    out = []
    for entry in comp.get("licenses", []):
        if "expression" in entry:
            out.append(entry["expression"])
        elif "license" in entry:
            out.append(entry["license"].get("id") or entry["license"].get("name", ""))
    return ", ".join(x for x in out if x)


def render(bom: dict) -> str:
    comps = sorted(bom["components"], key=lambda c: c["name"].lower())
    root_ref = bom.get("metadata", {}).get("component", {}).get("bom-ref", "")
    depends = {d["ref"]: sorted(d.get("dependsOn", []), key=str.lower)
               for d in bom.get("dependencies", [])}
    required_by: dict[str, list] = {}
    for ref, deps in depends.items():
        if ref == root_ref:
            continue  # everything traces to the root; listing it adds noise
        for dep in deps:
            required_by.setdefault(dep, []).append(ref)

    subject = bom.get("metadata", {}).get("component", {})
    types = {}
    for c in comps:
        types[c.get("type", "?")] = types.get(c.get("type", "?"), 0) + 1
    type_summary = ", ".join(f"{n} {t}" for t, n in sorted(types.items()))

    md = []
    md.append("# Software Bill of Materials")
    md.append("")
    md.append(f"Human-readable rendering of [sbom.cdx.json](sbom.cdx.json) "
              f"(CycloneDX {bom.get('specVersion', '?')}, document version "
              f"{bom.get('version', '?')}) for **{subject.get('name', '?')}** — "
              f"{subject.get('description', '')}")
    md.append("")
    md.append(f"**{len(comps)} components** ({type_summary}). "
              f"Generated by `{pathlib.Path(__file__).resolve().relative_to(ROOT)}`; "
              f"CI fails if this file is out of date with the CycloneDX source.")
    md.append("")
    md.append("## Summary")
    md.append("")
    md.append("Every component, sorted — each links to its entry (details and "
              "dependencies) in the section below.")
    md.append("")
    md.append("| Component | Type | Version / resolution | Supplier |")
    md.append("|---|---|---|---|")
    for c in comps:
        ver = c.get("version") or prop(c, "resolution") or "—"
        md.append(f"| [{c['name']}](#{slug(c['name'])}) | {c.get('type', '')} "
                  f"| {ver} | {c.get('supplier', {}).get('name', '')} |")
    md.append("")
    md.append("## Components & dependencies")
    md.append("")
    for c in comps:
        ref = c.get("bom-ref", c["name"])
        md.append(f"### {c['name']}")
        md.append("")
        rows = [("Type", c.get("type", ""))]
        if c.get("version"):
            rows.append(("Version", c["version"]))
        rows.append(("Supplier", c.get("supplier", {}).get("name", "")))
        if licenses(c):
            rows.append(("License", licenses(c)))
        if c.get("purl"):
            rows.append(("purl", f"`{c['purl']}`"))
        if prop(c, "resolution"):
            rows.append(("Resolution", prop(c, "resolution")))
        if prop(c, "note"):
            rows.append(("Note", prop(c, "note")))
        deps = depends.get(ref, [])
        rows.append(("Depends on / installs with it",
                     ", ".join(f"[{d}](#{slug(d)})" for d in deps) if deps else "—"))
        req = sorted(required_by.get(ref, []), key=str.lower)
        if req:
            rows.append(("Required by",
                         ", ".join(f"[{r}](#{slug(r)})" for r in req)))
        for k, v in rows:
            md.append(f"- **{k}:** {v}")
        md.append("")
    return "\n".join(md).rstrip() + "\n"


def main() -> int:
    bom = json.load(open(BOM))
    content = render(bom)
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != content:
            print(f"ERROR: {OUT.name} is out of date with {BOM.name} — "
                  f"regenerate with: python3 {pathlib.Path(__file__).resolve().relative_to(ROOT)}",
                  file=sys.stderr)
            return 1
        print(f"{OUT.name} is current.")
        return 0
    OUT.write_text(content)
    print(f"wrote {OUT.name} ({len(content.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
